import { Chapter, ClassLevel } from '@/types';

// Chapitres à exclure de l'affichage graphique (mais le contenu reste accessible)
const hiddenChapters = [
  '5eme-calcul-litteral-substitution',
  '5eme-calcul-litteral-developpement',
  '5eme-calcul-litteral-expressions-introduction',
  '5eme-calcul-litteral-expressions-regles',
  '5eme-calcul-litteral-factorisation',
  '5eme-priorites-operations',
  '4eme-thales-introduction',
  '4eme-thales-proportionnalite',
  '4eme-thales-reciproque',
  '4eme-thales-applications',
  '4eme-thales-contraposee'
];

export const chaptersData: Chapter[] = [
  // CE1 - Nouveau programme 2025
  {
    id: 'ce1-nombres-jusqu-1000',
    title: 'Nombres jusqu\'à 1000',
    description: 'Lecture, écriture et comparaison des nombres jusqu\'à 1000 (dès période 2)',
    classLevel: 'CE1',
    category: 'numeracy',
    difficulty: 'beginner',
    estimatedTime: 60,
    prerequisites: [],
    color: '#ff6b6b',
    icon: '1000',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 1,
    verified: true
  },
  {
    id: 'ce1-fractions-simples',
    title: 'Premières fractions',
    description: 'Fractions simples : demis, tiers, quarts (dès période 2)',
    classLevel: 'CE1',
    category: 'numeracy',
    difficulty: 'beginner',
    estimatedTime: 45,
    prerequisites: [],
    color: '#ff6b6b',
    icon: '½',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 2
  },
  {
    id: 'ce1-quatre-operations',
    title: 'Les quatre opérations',
    description: 'Addition, soustraction, multiplication et division (sens)',
    classLevel: 'CE1',
    category: 'numeracy',
    difficulty: 'beginner',
    estimatedTime: 70,
    prerequisites: [],
    color: '#ff6b6b',
    icon: '➕',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 3
  },
  {
    id: 'ce1-calcul-mental',
    title: 'Calcul mental',
    description: 'Automatisation des calculs, stratégies mentales',
    classLevel: 'CE1',
    category: 'numeracy',
    difficulty: 'beginner',
    estimatedTime: 45,
    prerequisites: [],
    color: '#ff6b6b',
    icon: '🧠',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 4
  },
  {
    id: 'ce1-resolution-problemes',
    title: 'Résolution de problèmes',
    description: 'Problèmes à une ou deux étapes, typologie des problèmes',
    classLevel: 'CE1',
    category: 'numeracy',
    difficulty: 'beginner',
    estimatedTime: 50,
    prerequisites: [],
    color: '#ff6b6b',
    icon: '❓',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 5
  },
  {
    id: 'ce1-grandeurs-mesures',
    title: 'Grandeurs et mesures',
    description: 'Longueurs (m, cm, km), masses (g, kg), monnaie, temps',
    classLevel: 'CE1',
    category: 'geometry',
    difficulty: 'beginner',
    estimatedTime: 40,
    prerequisites: [],
    color: '#ff6b6b',
    icon: '📏',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 6
  },
  {
    id: 'ce1-espace-geometrie',
    title: 'Espace et géométrie',
    description: 'Figures géométriques, repérage dans l\'espace',
    classLevel: 'CE1',
    category: 'geometry',
    difficulty: 'beginner',
    estimatedTime: 40,
    prerequisites: [],
    color: '#ff6b6b',
    icon: '🔺',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 7
  },
  {
    id: 'ce1-gestion-donnees',
    title: 'Organisation et gestion de données',
    description: 'Tableaux, graphiques simples',
    classLevel: 'CE1',
    category: 'data',
    difficulty: 'beginner',
    estimatedTime: 30,
    prerequisites: [],
    color: '#ff6b6b',
    icon: '📊',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 8
  },

  // CE2 - Nouveau programme 2025
  {
    id: 'ce2-nombres-jusqu-10000',
    title: 'Nombres jusqu\'à 10 000',
    description: 'Maîtrise des nombres jusqu\'à 10 000 (dès période 2)',
    classLevel: 'CE2',
    category: 'numeracy',
    difficulty: 'beginner',
    estimatedTime: 60,
    prerequisites: [],
    color: '#4ecdc4',
    icon: '10000',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 9
  },
  {
    id: 'ce2-fractions-bande-unite',
    title: 'Fractions et mesures',
    description: 'Fractions sur bande-unité, mesures de grandeurs',
    classLevel: 'CE2',
    category: 'numeracy',
    difficulty: 'beginner',
    estimatedTime: 50,
    prerequisites: [],
    color: '#4ecdc4',
    icon: '½',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 10
  },
  {
    id: 'ce2-operations-complexes',
    title: 'Opérations complexes',
    description: 'Multiplication posée (période 4), division euclidienne',
    classLevel: 'CE2',
    category: 'numeracy',
    difficulty: 'beginner',
    estimatedTime: 70,
    prerequisites: [],
    color: '#4ecdc4',
    icon: '✖️',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 11
  },
  {
    id: 'ce2-calcul-mental-avance',
    title: 'Calcul mental avancé',
    description: 'Stratégies élaborées, procédures automatisées',
    classLevel: 'CE2',
    category: 'numeracy',
    difficulty: 'intermediate',
    estimatedTime: 45,
    prerequisites: [],
    color: '#4ecdc4',
    icon: '🧠',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 12
  },
  {
    id: 'ce2-resolution-problemes-avance',
    title: 'Résolution de problèmes avancée',
    description: 'Problèmes à plusieurs étapes, représentations variées',
    classLevel: 'CE2',
    category: 'numeracy',
    difficulty: 'intermediate',
    estimatedTime: 60,
    prerequisites: [],
    color: '#4ecdc4',
    icon: '❓',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 13
  },
  {
    id: 'ce2-grandeurs-mesures-avance',
    title: 'Grandeurs et mesures avancées',
    description: 'Périmètres, contenances (L, dL, cL), conversions',
    classLevel: 'CE2',
    category: 'geometry',
    difficulty: 'intermediate',
    estimatedTime: 50,
    prerequisites: [],
    color: '#4ecdc4',
    icon: '📏',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 14
  },
  {
    id: 'ce2-geometrie-proprietes',
    title: 'Géométrie et propriétés',
    description: 'Propriétés des figures, angles (aigu/obtus), symétrie',
    classLevel: 'CE2',
    category: 'geometry',
    difficulty: 'intermediate',
    estimatedTime: 45,
    prerequisites: [],
    color: '#4ecdc4',
    icon: '🔺',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 15
  },
  {
    id: 'ce2-gestion-donnees-avance',
    title: 'Gestion de données avancée',
    description: 'Diagrammes en barres, résolution de problèmes avec données',
    classLevel: 'CE2',
    category: 'data',
    difficulty: 'intermediate',
    estimatedTime: 40,
    prerequisites: [],
    color: '#4ecdc4',
    icon: '📊',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 16
  },

  // CM1 - Nouveau programme 2025
  {
    id: 'nombres-entiers-jusqu-au-million',
    title: 'Nombres entiers jusqu\'au million',
    description: 'Lire, écrire, décomposer et représenter les nombres jusqu\'au million',
    classLevel: 'CM1',
    category: 'numeracy',
    difficulty: 'intermediate',
    estimatedTime: 70,
    prerequisites: [],
    color: '#45b7d1',
    icon: '🔢',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 17
  },
  {
    id: 'cm1-nombres-decimaux',
    title: 'Nombres décimaux',
    description: 'Nombres décimaux, écriture à virgule',
    classLevel: 'CM1',
    category: 'numeracy',
    difficulty: 'intermediate',
    estimatedTime: 70,
    prerequisites: [],
    color: '#45b7d1',
    icon: '12,5',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 18
  },
  {
    id: 'cm1-fractions-equivalentes',
    title: 'Fractions équivalentes',
    description: 'Fractions équivalentes, comparaison, opérations',
    classLevel: 'CM1',
    category: 'numeracy',
    difficulty: 'intermediate',
    estimatedTime: 60,
    prerequisites: [],
    color: '#45b7d1',
    icon: '½',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 19
  },
  {
    id: 'cm1-operations-arithmetiques',
    title: 'Opérations arithmétiques',
    description: 'Additions, soustractions, multiplications et divisions posées en colonnes, avec nombres entiers et décimaux simples',
    classLevel: 'CM1',
    category: 'numeracy',
    difficulty: 'intermediate',
    estimatedTime: 80,
    prerequisites: [],
    color: '#45b7d1',
    icon: '➕',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 20
  },
  {
    id: 'cm1-calcul-mental',
    title: 'Calcul mental',
    description: 'Développer des stratégies de calcul rapide et des automatismes',
    classLevel: 'CM1',
    category: 'numeracy',
    difficulty: 'intermediate',
    estimatedTime: 60,
    prerequisites: [],
    color: '#45b7d1',
    icon: '🧠',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 21
  },
  {
    id: 'cm1-grandeurs-mesures',
    title: 'Grandeurs et mesures',
    description: 'Longueurs, masses, contenances, angles, temps et durées ; estimations, conversions simples et résolution de problèmes',
    classLevel: 'CM1',
    category: 'geometry',
    difficulty: 'intermediate',
    estimatedTime: 70,
    prerequisites: [],
    color: '#45b7d1',
    icon: '📏',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 21
  },
  {
    id: 'cm1-raisonnement-inconnues',
    title: 'Raisonnement avec inconnues',
    description: 'Introduction aux égalités avec symboles, diagrammes en barres pour résoudre des problèmes simples',
    classLevel: 'CM1',
    category: 'numeracy',
    difficulty: 'intermediate',
    estimatedTime: 40,
    prerequisites: [],
    color: '#45b7d1',
    icon: '🧮',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 22
  },
  {
    id: 'cm1-resolution-problemes',
    title: 'Résolution de problèmes',
    description: 'Problèmes additifs et multiplicatifs en 1-3 étapes, avec optimisation et comparaison',
    classLevel: 'CM1',
    category: 'numeracy',
    difficulty: 'intermediate',
    estimatedTime: 60,
    prerequisites: [],
    color: '#45b7d1',
    icon: '🤔',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 23
  },
  {
    id: 'cm1-probabilites',
    title: 'Probabilités (nouveau)',
    description: 'Premières expériences aléatoires, certains/impossibles',
    classLevel: 'CM1',
    category: 'statistics',
    difficulty: 'intermediate',
    estimatedTime: 40,
    prerequisites: [],
    color: '#45b7d1',
    icon: '🎲',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 24
  },
  {
    id: 'cm1-proportionnalite',
    title: 'Proportionnalité',
    description: 'Situations de proportionnalité, pourcentages simples',
    classLevel: 'CM1',
    category: 'numeracy',
    difficulty: 'intermediate',
    estimatedTime: 55,
    prerequisites: [],
    color: '#45b7d1',
    icon: '%',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 25
  },
  {
    id: 'cm1-aires-perimetres',
    title: 'Aires et périmètres',
    description: 'Mesure et comparaison des aires et périmètres des figures géométriques',
    classLevel: 'CM1',
    category: 'geometry',
    difficulty: 'intermediate',
    estimatedTime: 60,
    prerequisites: [],
    color: '#45b7d1',
    icon: '□',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 26
  },
  {
    id: 'cm1-geometrie-construction',
    title: 'Géométrie et construction',
    description: 'Construction de figures, propriétés géométriques',
    classLevel: 'CM1',
    category: 'geometry',
    difficulty: 'intermediate',
    estimatedTime: 45,
    prerequisites: [],
    color: '#45b7d1',
    icon: '📐',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 27
  },
  {
    id: 'cm1-algorithmes-programmation',
    title: 'Algorithmes et programmation',
    description: 'Premières notions d\'algorithmes, Scratch débutant',
    classLevel: 'CM1',
    category: 'programming',
    difficulty: 'intermediate',
    estimatedTime: 35,
    prerequisites: [],
    color: '#45b7d1',
    icon: '🖥️',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 28
  },
  {
    id: 'cm1-statistiques-graphiques',
    title: 'Statistiques et graphiques',
    description: 'Traitement de données, graphiques complexes',
    classLevel: 'CM1',
    category: 'statistics',
    difficulty: 'intermediate',
    estimatedTime: 40,
    prerequisites: [],
    color: '#45b7d1',
    icon: '📈',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 29
  },

  // CM2 - Nouveau programme 2025
  {
    id: 'cm2-nombres-rationnels',
    title: 'Nombres rationnels',
    description: 'Fractions et décimaux, nombres relatifs (initiation)',
    classLevel: 'CM2',
    category: 'numeracy',
    difficulty: 'intermediate',
    estimatedTime: 70,
    prerequisites: [],
    color: '#96ceb4',
    icon: '±',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 25
  },
  {
    id: 'cm2-operations-avancees',
    title: 'Opérations avancées',
    description: 'Opérations sur décimaux, division décimale',
    classLevel: 'CM2',
    category: 'numeracy',
    difficulty: 'intermediate',
    estimatedTime: 65,
    prerequisites: [],
    color: '#96ceb4',
    icon: '➕',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 26
  },
  {
    id: 'cm2-angles-mesures',
    title: 'Angles et mesures',
    description: 'Mesure d\'angles, rapporteur, propriétés',
    classLevel: 'CM2',
    category: 'geometry',
    difficulty: 'intermediate',
    estimatedTime: 50,
    prerequisites: [],
    color: '#96ceb4',
    icon: '∠',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 27
  },
  {
    id: 'cm2-proportionnalite-avance',
    title: 'Proportionnalité avancée',
    description: 'Tableaux de proportionnalité, règle de trois, échelles',
    classLevel: 'CM2',
    category: 'numeracy',
    difficulty: 'intermediate',
    estimatedTime: 55,
    prerequisites: [],
    color: '#96ceb4',
    icon: '%',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 28
  },
  {
    id: 'cm2-probabilites-avance',
    title: 'Probabilités avancées',
    description: 'Calcul de probabilités simples, expériences aléatoires',
    classLevel: 'CM2',
    category: 'statistics',
    difficulty: 'intermediate',
    estimatedTime: 45,
    prerequisites: [],
    color: '#96ceb4',
    icon: '🎲',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 29
  },
  {
    id: 'cm2-algorithmes-avance',
    title: 'Algorithmes avancés',
    description: 'Structures de contrôle, boucles, Scratch intermédiaire',
    classLevel: 'CM2',
    category: 'programming',
    difficulty: 'intermediate',
    estimatedTime: 40,
    prerequisites: [],
    color: '#96ceb4',
    icon: '🖥️',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 30
  },
  {
    id: 'cm2-statistiques-avance',
    title: 'Statistiques avancées',
    description: 'Moyennes, médiane, interprétation de données',
    classLevel: 'CM2',
    category: 'statistics',
    difficulty: 'intermediate',
    estimatedTime: 45,
    prerequisites: [],
    color: '#96ceb4',
    icon: '📊',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 31
  },

  // 6ème - Nouveau programme 2025
  {
    id: '6eme-nombres-entiers',
    title: 'Nombres entiers',
    description: 'Nombres entiers, divisibilité, nombres premiers',
    classLevel: '6eme',
    category: 'numeracy',
    difficulty: 'intermediate',
    estimatedTime: 75,
    prerequisites: [],
    color: '#feca57',
    icon: '123',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 32
  },
  {
    id: '6eme-fractions-decimaux',
    title: 'Fractions et décimaux',
    description: 'Fractions, décimaux, pourcentages, conversions',
    classLevel: '6eme',
    category: 'numeracy',
    difficulty: 'intermediate',
    estimatedTime: 80,
    prerequisites: [],
    color: '#feca57',
    icon: '½',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 33
  },
  {
    id: '6eme-geometrie-plane',
    title: 'Géométrie plane',
    description: 'Figures géométriques, constructions, propriétés',
    classLevel: '6eme',
    category: 'geometry',
    difficulty: 'intermediate',
    estimatedTime: 70,
    prerequisites: [],
    color: '#feca57',
    icon: '🔺',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 34
  },
  {
    id: '6eme-proportionnalite-applications',
    title: 'Proportionnalité et applications',
    description: 'Proportionnalité, pourcentages, vitesses, échelles',
    classLevel: '6eme',
    category: 'numeracy',
    difficulty: 'intermediate',
    estimatedTime: 60,
    prerequisites: [],
    color: '#feca57',
    icon: '%',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 35
  },
  {
    id: '6eme-statistiques-initiation',
    title: 'Statistiques (initiation)',
    description: 'Vocabulaire statistique, graphiques, moyennes',
    classLevel: '6eme',
    category: 'statistics',
    difficulty: 'intermediate',
    estimatedTime: 50,
    prerequisites: [],
    color: '#feca57',
    icon: '📊',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 36
  },
  {
    id: '6eme-algorithmes-scratch',
    title: 'Algorithmes et Scratch',
    description: 'Programmation avec Scratch, algorithmes simples',
    classLevel: '6eme',
    category: 'programming',
    difficulty: 'intermediate',
    estimatedTime: 45,
    prerequisites: [],
    color: '#feca57',
    icon: '🖥️',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 37
  },

  // 5ème - Cycle 4
  {
    id: '5eme-nombres-relatifs',
    title: 'Nombres relatifs',
    description: 'Nombres relatifs, opérations, droite graduée',
    classLevel: '5eme',
    category: 'numeracy',
    difficulty: 'intermediate',
    estimatedTime: 70,
    prerequisites: [],
    color: '#ff9ff3',
    icon: '±',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 38
  },
  {
    id: '5eme-fractions-rationnels',
    title: 'Nombres rationnels et fractions',
    description: 'Approfondissement des fractions (opérations, simplification, comparaison), introduction aux nombres rationnels',
    classLevel: '5eme',
    category: 'numeracy',
    difficulty: 'intermediate',
    estimatedTime: 75,
    prerequisites: [],
    color: '#ff9ff3',
    icon: '½',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 39
  },
  {
    id: '5eme-calcul-litteral',
    title: 'Calcul littéral',
    description: 'Expressions littérales, développement, factorisation',
    classLevel: '5eme',
    category: 'algebra',
    difficulty: 'intermediate',
    estimatedTime: 65,
    prerequisites: [],
    color: '#ff9ff3',
    icon: 'x',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 40,
    verified: true
  },
  {
    id: '5eme-calcul-litteral-expressions-introduction',
    title: 'Introduction',
    description: 'Définitions, vocabulaire et astuce avec les chats 🐱',
    classLevel: '5eme',
    category: 'algebra',
    difficulty: 'beginner',
    estimatedTime: 8,
    prerequisites: [],
    color: '#ff9ff3',
    icon: '🎯',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 40.1,
    parentChapter: '5eme-calcul-litteral',
    verified: true
  },
  {
    id: '5eme-calcul-litteral-expressions-regles',
    title: 'Règles de calcul',
    description: 'Addition et multiplication avec animations 🐱',
    classLevel: '5eme',
    category: 'algebra',
    difficulty: 'beginner',
    estimatedTime: 12,
    prerequisites: ['5eme-calcul-litteral-expressions-introduction'],
    color: '#ff9ff3',
    icon: '📐',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 40.2,
    parentChapter: '5eme-calcul-litteral',
    verified: true
  },
  {
    id: '5eme-calcul-litteral-developpement',
    title: 'Développement',
    description: 'Utiliser la distributivité pour développer',
    classLevel: '5eme',
    category: 'algebra',
    difficulty: 'intermediate',
    estimatedTime: 25,
    prerequisites: ['5eme-calcul-litteral-expressions-regles'],
    color: '#ff9ff3',
    icon: '📐',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 40.3,
    parentChapter: '5eme-calcul-litteral',
    verified: true
  },
  {
    id: '5eme-calcul-litteral-substitution',
    title: 'Substitution',
    description: 'Remplacer les variables par des valeurs numériques',
    classLevel: '5eme',
    category: 'algebra',
    difficulty: 'beginner',
    estimatedTime: 15,
    prerequisites: ['5eme-calcul-litteral-expressions-regles'],
    color: '#ff9ff3',
    icon: '🔢',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 40.4,
    parentChapter: '5eme-calcul-litteral',
    verified: true
  },
  {
    id: '5eme-calcul-litteral-factorisation',
    title: 'Factorisation',
    description: 'Factoriser des expressions littérales simples',
    classLevel: '5eme',
    category: 'algebra',
    difficulty: 'intermediate',
    estimatedTime: 20,
    prerequisites: ['5eme-calcul-litteral-developpement'],
    color: '#ff9ff3',
    icon: '🎯',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 40.5,
    parentChapter: '5eme-calcul-litteral',
    verified: true
  },
  {
    id: '5eme-priorites-operations',
    title: 'Priorités des opérations',
    description: 'Ordre des opérations, expressions numériques',
    classLevel: '5eme',
    category: 'numeracy',
    difficulty: 'intermediate',
    estimatedTime: 50,
    prerequisites: [],
    color: '#ff9ff3',
    icon: '( )',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 41
  },
  {
    id: '5eme-proportionnalite',
    title: 'Proportionnalité',
    description: 'Situations de proportionnalité (tableaux, coefficients, pourcentages, échelles), résolution de problèmes concrets',
    classLevel: '5eme',
    category: 'numeracy',
    difficulty: 'intermediate',
    estimatedTime: 60,
    prerequisites: [],
    color: '#ff9ff3',
    icon: '%',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 42
  },
  {
    id: '5eme-triangles-parallelogrammes',
    title: 'Triangles et parallélogrammes',
    description: 'Propriétés des triangles et parallélogrammes',
    classLevel: '5eme',
    category: 'geometry',
    difficulty: 'intermediate',
    estimatedTime: 60,
    prerequisites: [],
    color: '#ff9ff3',
    icon: '▲',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 43
  },
  {
    id: '5eme-grandeurs-mesures',
    title: 'Grandeurs et mesures',
    description: 'Périmètres, aires (triangles, parallélogrammes), volumes simples (prismes, cylindres), conversions d\'unités, angles',
    classLevel: '5eme',
    category: 'geometry',
    difficulty: 'intermediate',
    estimatedTime: 70,
    prerequisites: [],
    color: '#ff9ff3',
    icon: '📏',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 44
  },
  {
    id: '5eme-symetrie-reperage',
    title: 'Symétrie centrale et repérage',
    description: 'Symétrie centrale (construction, propriétés), repérage dans le plan (coordonnées cartésiennes, distances)',
    classLevel: '5eme',
    category: 'geometry',
    difficulty: 'intermediate',
    estimatedTime: 55,
    prerequisites: [],
    color: '#ff9ff3',
    icon: '🔄',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 45
  },
  {
    id: '5eme-fonctions',
    title: 'Fonctions',
    description: 'Initiation aux fonctions (représentation graphique, tableaux de valeurs), lien avec proportionnalité',
    classLevel: '5eme',
    category: 'algebra',
    difficulty: 'intermediate',
    estimatedTime: 50,
    prerequisites: [],
    color: '#ff9ff3',
    icon: 'ƒ',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 46
  },
  {
    id: '5eme-statistiques-probabilites',
    title: 'Statistiques et probabilités',
    description: 'Statistiques descriptives, probabilités',
    classLevel: '5eme',
    category: 'statistics',
    difficulty: 'intermediate',
    estimatedTime: 55,
    prerequisites: [],
    color: '#ff9ff3',
    icon: '📊',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 47
  },
  {
    id: '5eme-algorithmes-python',
    title: 'Algorithmes et Python',
    description: 'Introduction à Python, algorithmes de base',
    classLevel: '5eme',
    category: 'programming',
    difficulty: 'intermediate',
    estimatedTime: 45,
    prerequisites: [],
    color: '#ff9ff3',
    icon: '🐍',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 48
  },
  {
    id: '5eme-resolution-problemes',
    title: 'Résolution de problèmes transversale',
    description: 'Problèmes en 2-3 étapes impliquant plusieurs domaines, modélisation (diagrammes, équations simples)',
    classLevel: '5eme',
    category: 'numeracy',
    difficulty: 'intermediate',
    estimatedTime: 55,
    prerequisites: [],
    color: '#ff9ff3',
    icon: '🧩',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 49
  },

  // 4ème - Cycle 4
  {
    id: '4eme-calculs-relatifs',
    title: 'Calculs avec les relatifs',
    description: 'Opérations sur les nombres relatifs',
    classLevel: '4eme',
    category: 'numeracy',
    difficulty: 'intermediate',
    estimatedTime: 60,
    prerequisites: [],
    color: '#54a0ff',
    icon: '±',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 50
  },
  {
    id: '4eme-puissances',
    title: 'Puissances',
    description: 'Puissances de 10, notation scientifique',
    classLevel: '4eme',
    category: 'numeracy',
    difficulty: 'intermediate',
    estimatedTime: 55,
    prerequisites: [],
    color: '#54a0ff',
    icon: '10²',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 51
  },
  {
    id: '4eme-theoreme-pythagore',
    title: 'Théorème de Pythagore',
    description: 'Théorème de Pythagore et sa réciproque',
    classLevel: '4eme',
    category: 'geometry',
    difficulty: 'intermediate',
    estimatedTime: 93,
    prerequisites: [],
    color: '#3b82f6',
    icon: 'a²+b²',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 52
  },
  {
    id: '4eme-pythagore-introduction',
    title: 'Introduction et découverte',
    description: 'Découvrir le théorème de Pythagore avec des animations 🔺',
    classLevel: '4eme',
    category: 'geometry',
    difficulty: 'beginner',
    estimatedTime: 15,
    prerequisites: [],
    color: '#3b82f6',
    icon: '🔺',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 52.1,
    parentChapter: '4eme-theoreme-pythagore'
  },
  {
    id: '4eme-pythagore-calculs-directs',
    title: 'Calculs directs',
    description: 'Calculer l\'hypoténuse d\'un triangle rectangle 📏',
    classLevel: '4eme',
    category: 'geometry',
    difficulty: 'intermediate',
    estimatedTime: 18,
    prerequisites: ['4eme-pythagore-introduction'],
    color: '#3b82f6',
    icon: '📏',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 52.2,
    parentChapter: '4eme-theoreme-pythagore'
  },
  {
    id: '4eme-pythagore-calculs-inverses',
    title: 'Calculs inverses',
    description: 'Calculer un côté de l\'angle droit 🔄',
    classLevel: '4eme',
    category: 'geometry',
    difficulty: 'intermediate',
    estimatedTime: 20,
    prerequisites: ['4eme-pythagore-calculs-directs'],
    color: '#3b82f6',
    icon: '🔄',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 52.3,
    parentChapter: '4eme-theoreme-pythagore'
  },
  {
    id: '4eme-pythagore-applications',
    title: 'Applications et problèmes',
    description: 'Résoudre des problèmes concrets avec Pythagore 🏗️',
    classLevel: '4eme',
    category: 'geometry',
    difficulty: 'intermediate',
    estimatedTime: 22,
    prerequisites: ['4eme-pythagore-calculs-inverses'],
    color: '#3b82f6',
    icon: '🏗️',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 52.4,
    parentChapter: '4eme-theoreme-pythagore'
  },
  {
    id: '4eme-pythagore-reciproque',
    title: 'Réciproque du théorème',
    description: 'Démontrer qu\'un triangle est rectangle ✅',
    classLevel: '4eme',
    category: 'geometry',
    difficulty: 'advanced',
    estimatedTime: 18,
    prerequisites: ['4eme-pythagore-applications'],
    color: '#3b82f6',
    icon: '✅',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 52.5,
    parentChapter: '4eme-theoreme-pythagore'
  },
  {
    id: '4eme-equations',
    title: 'Introduction aux équations',
    description: 'Notion d\'équation et premières résolutions simples du premier degré',
    classLevel: '4eme',
    category: 'algebra',
    difficulty: 'intermediate',
    estimatedTime: 50,
    prerequisites: [],
    color: '#54a0ff',
    icon: 'x=?',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 53,
    verified: true
  },
  {
    id: '4eme-calcul-litteral',
    title: 'Calcul littéral',
    description: 'Expressions littérales, développement, factorisation',
    classLevel: '4eme',
    category: 'algebra',
    difficulty: 'intermediate',
    estimatedTime: 65,
    prerequisites: [],
    color: '#54a0ff',
    icon: 'x',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 54,
    verified: true
  },
  {
    id: '4eme-calcul-litteral-expressions-introduction',
    title: 'Introduction',
    description: 'Définitions, vocabulaire et astuce avec les chats 🐱',
    classLevel: '4eme',
    category: 'algebra',
    difficulty: 'beginner',
    estimatedTime: 8,
    prerequisites: [],
    color: '#54a0ff',
    icon: '🎯',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 54.1,
    parentChapter: '4eme-calcul-litteral',
    verified: true
  },
  {
    id: '4eme-calcul-litteral-expressions-regles',
    title: 'Règles de calcul',
    description: 'Addition et multiplication avec animations 🐱',
    classLevel: '4eme',
    category: 'algebra',
    difficulty: 'beginner',
    estimatedTime: 12,
    prerequisites: ['4eme-calcul-litteral-expressions-introduction'],
    color: '#54a0ff',
    icon: '📐',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 54.2,
    parentChapter: '4eme-calcul-litteral',
    verified: true
  },
  {
    id: '4eme-calcul-litteral-developpement',
    title: 'Développement',
    description: 'Utiliser la distributivité pour développer',
    classLevel: '4eme',
    category: 'algebra',
    difficulty: 'intermediate',
    estimatedTime: 25,
    prerequisites: ['4eme-calcul-litteral-expressions-regles'],
    color: '#54a0ff',
    icon: '📐',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 54.3,
    parentChapter: '4eme-calcul-litteral',
    verified: true
  },
  {
    id: '4eme-calcul-litteral-substitution',
    title: 'Substitution',
    description: 'Remplacer les variables par des valeurs numériques',
    classLevel: '4eme',
    category: 'algebra',
    difficulty: 'beginner',
    estimatedTime: 15,
    prerequisites: ['4eme-calcul-litteral-expressions-regles'],
    color: '#54a0ff',
    icon: '🔢',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 54.4,
    parentChapter: '4eme-calcul-litteral',
    verified: true
  },
  {
    id: '4eme-calcul-litteral-factorisation',
    title: 'Factorisation',
    description: 'Factoriser des expressions littérales',
    classLevel: '4eme',
    category: 'algebra',
    difficulty: 'intermediate',
    estimatedTime: 25,
    prerequisites: ['4eme-calcul-litteral-developpement'],
    color: '#54a0ff',
    icon: '🎯',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 54.45,
    parentChapter: '4eme-calcul-litteral',
    verified: true
  },
  {
    id: '4eme-calcul-litteral-problemes',
    title: 'Problèmes',
    description: 'Problèmes concrets utilisant le calcul littéral',
    classLevel: '4eme',
    category: 'algebra',
    difficulty: 'intermediate',
    estimatedTime: 20,
    prerequisites: ['4eme-calcul-litteral-substitution'],
    color: '#ff6b6b',
    icon: '🧩',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 54.5,
    parentChapter: '4eme-calcul-litteral',
    verified: true
  },
  {
    id: '4eme-cosinus',
    title: 'Cosinus',
    description: 'Cosinus d\'un angle aigu, applications',
    classLevel: '4eme',
    category: 'geometry',
    difficulty: 'intermediate',
    estimatedTime: 75,
    prerequisites: [],
    color: '#e74c3c',
    icon: 'cos',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 55
  },
  {
    id: '4eme-cosinus-introduction',
    title: 'Introduction au cosinus',
    description: 'Découvrir le cosinus dans le triangle rectangle avec animations 📐',
    classLevel: '4eme',
    category: 'geometry',
    difficulty: 'beginner',
    estimatedTime: 15,
    prerequisites: [],
    color: '#e74c3c',
    icon: '📐',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 55.1,
    parentChapter: '4eme-cosinus'
  },
  {
    id: '4eme-cosinus-calculs',
    title: 'Calculs et valeurs remarquables',
    description: 'Calculer le cosinus et mémoriser les valeurs importantes 🧮',
    classLevel: '4eme',
    category: 'geometry',
    difficulty: 'intermediate',
    estimatedTime: 20,
    prerequisites: ['4eme-cosinus-introduction'],
    color: '#e74c3c',
    icon: '🧮',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 55.2,
    parentChapter: '4eme-cosinus'
  },
  {
    id: '4eme-cosinus-applications',
    title: 'Applications et problèmes',
    description: 'Résoudre des problèmes concrets avec le cosinus 🏗️',
    classLevel: '4eme',
    category: 'geometry',
    difficulty: 'intermediate',
    estimatedTime: 18,
    prerequisites: ['4eme-cosinus-calculs'],
    color: '#e74c3c',
    icon: '🏗️',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 55.3,
    parentChapter: '4eme-cosinus'
  },
  {
    id: '4eme-cosinus-constructions',
    title: 'Constructions géométriques',
    description: 'Construire des angles et des figures avec le cosinus 📏',
    classLevel: '4eme',
    category: 'geometry',
    difficulty: 'intermediate',
    estimatedTime: 22,
    prerequisites: ['4eme-cosinus-applications'],
    color: '#e74c3c',
    icon: '📏',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 55.4,
    parentChapter: '4eme-cosinus'
  },
  {
    id: '4eme-theoreme-thales',
    title: 'Théorème de Thalès',
    description: 'Théorème de Thalès et ses applications en géométrie',
    classLevel: '4eme',
    category: 'geometry',
    difficulty: 'intermediate',
    estimatedTime: 85,
    prerequisites: [],
    color: '#10b981',
    icon: '⫽',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 55.5
  },
  {
    id: '4eme-thales-introduction',
    title: 'Introduction et découverte',
    description: 'Découvrir le théorème de Thalès avec des animations 📐',
    classLevel: '4eme',
    category: 'geometry',
    difficulty: 'beginner',
    estimatedTime: 15,
    prerequisites: [],
    color: '#10b981',
    icon: '📐',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 55.51,
    parentChapter: '4eme-theoreme-thales'
  },
  {
    id: '4eme-thales-proportionnalite',
    title: 'Proportionnalité et calculs',
    description: 'Calculer des longueurs avec le théorème de Thalès 📏',
    classLevel: '4eme',
    category: 'geometry',
    difficulty: 'intermediate',
    estimatedTime: 20,
    prerequisites: ['4eme-thales-introduction'],
    color: '#10b981',
    icon: '📏',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 55.52,
    parentChapter: '4eme-theoreme-thales'
  },
  {
    id: '4eme-thales-reciproque',
    title: 'Réciproque du théorème',
    description: 'Démontrer le parallélisme avec la réciproque 🔄',
    classLevel: '4eme',
    category: 'geometry',
    difficulty: 'intermediate',
    estimatedTime: 18,
    prerequisites: ['4eme-thales-proportionnalite'],
    color: '#10b981',
    icon: '🔄',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 55.53,
    parentChapter: '4eme-theoreme-thales'
  },
  {
    id: '4eme-thales-applications',
    title: 'Applications et problèmes',
    description: 'Résoudre des problèmes concrets avec Thalès 🏗️',
    classLevel: '4eme',
    category: 'geometry',
    difficulty: 'intermediate',
    estimatedTime: 22,
    prerequisites: ['4eme-thales-reciproque'],
    color: '#10b981',
    icon: '🏗️',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 55.54,
    parentChapter: '4eme-theoreme-thales'
  },
  {
    id: '4eme-thales-contraposee',
    title: 'Contraposée et non-parallélisme',
    description: 'Prouver qu\'il n\'y a pas de parallélisme ❌',
    classLevel: '4eme',
    category: 'geometry',
    difficulty: 'advanced',
    estimatedTime: 15,
    prerequisites: ['4eme-thales-applications'],
    color: '#10b981',
    icon: '❌',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 55.55,
    parentChapter: '4eme-theoreme-thales'
  },
  {
    id: '4eme-statistiques-avancees',
    title: 'Statistiques avancées',
    description: 'Statistiques à deux variables, corrélation',
    classLevel: '4eme',
    category: 'statistics',
    difficulty: 'intermediate',
    estimatedTime: 50,
    prerequisites: [],
    color: '#54a0ff',
    icon: '📊',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 56
  },
  {
    id: '4eme-algorithmes-avances',
    title: 'Algorithmes avancés',
    description: 'Algorithmes complexes, fonctions en Python',
    classLevel: '4eme',
    category: 'programming',
    difficulty: 'intermediate',
    estimatedTime: 45,
    prerequisites: [],
    color: '#54a0ff',
    icon: '🐍',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 56
  },

  // 3ème - Cycle 4
  {
    id: '3eme-arithmetique',
    title: 'Arithmétique',
    description: 'PGCD, PPCM, nombres premiers, fractions irréductibles',
    classLevel: '3eme',
    category: 'numeracy',
    difficulty: 'intermediate',
    estimatedTime: 65,
    prerequisites: [],
    color: '#5f27cd',
    icon: '∞',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 57
  },
  {
    id: '3eme-calcul-litteral-avance',
    title: 'Calcul littéral avancé',
    description: 'Identités remarquables, développement, factorisation',
    classLevel: '3eme',
    category: 'algebra',
    difficulty: 'intermediate',
    estimatedTime: 70,
    prerequisites: [],
    color: '#5f27cd',
    icon: '(a+b)²',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 58
  },
  {
    id: '3eme-equations-systemes',
    title: 'Équations et systèmes',
    description: 'Équations du premier degré, systèmes d\'équations',
    classLevel: '3eme',
    category: 'algebra',
    difficulty: 'intermediate',
    estimatedTime: 65,
    prerequisites: [],
    color: '#5f27cd',
    icon: '{x,y}',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 59
  },
  {
    id: '3eme-fonctions-lineaires',
    title: 'Fonctions linéaires et affines',
    description: 'Fonctions linéaires, affines, représentations graphiques',
    classLevel: '3eme',
    category: 'functions',
    difficulty: 'intermediate',
    estimatedTime: 75,
    prerequisites: [],
    color: '#5f27cd',
    icon: 'f(x)',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 60
  },
  {
    id: '3eme-trigonometrie',
    title: 'Trigonométrie',
    description: 'Sinus, cosinus, tangente dans le triangle rectangle',
    classLevel: '3eme',
    category: 'geometry',
    difficulty: 'intermediate',
    estimatedTime: 60,
    prerequisites: [],
    color: '#5f27cd',
    icon: 'sin',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 61
  },
  {
    id: '3eme-geometrie-espace',
    title: 'Géométrie dans l\'espace',
    description: 'Solides, sections, volumes',
    classLevel: '3eme',
    category: 'geometry',
    difficulty: 'intermediate',
    estimatedTime: 55,
    prerequisites: [],
    color: '#5f27cd',
    icon: '🔺',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 62
  },
  {
    id: '3eme-statistiques-probabilites-avance',
    title: 'Statistiques et probabilités',
    description: 'Statistiques descriptives, probabilités conditionnelles',
    classLevel: '3eme',
    category: 'statistics',
    difficulty: 'intermediate',
    estimatedTime: 50,
    prerequisites: [],
    color: '#5f27cd',
    icon: '📊',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 63
  },
  {
    id: '3eme-algorithmes-projet',
    title: 'Algorithmes et projets',
    description: 'Projets algorithmiques, Python avancé',
    classLevel: '3eme',
    category: 'programming',
    difficulty: 'intermediate',
    estimatedTime: 45,
    prerequisites: [],
    color: '#5f27cd',
    icon: '🐍',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 64
  },

  // 2nde - Lycée
  {
    id: '2nde-ensembles-nombres',
    title: 'Ensembles de nombres',
    description: 'Ensembles ℕ, ℤ, ℚ, ℝ, intervalles',
    classLevel: '2nde',
    category: 'numeracy',
    difficulty: 'intermediate',
    estimatedTime: 60,
    prerequisites: [],
    color: '#ff6b6b',
    icon: 'ℝ',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 65
  },
  {
    id: '2nde-fonctions-generalites',
    title: 'Fonctions : généralités',
    description: 'Notion de fonction, domaine, image, représentation',
    classLevel: '2nde',
    category: 'functions',
    difficulty: 'intermediate',
    estimatedTime: 70,
    prerequisites: [],
    color: '#ff6b6b',
    icon: 'f(x)',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 66
  },
  {
    id: '2nde-equations-inequations',
    title: 'Équations et inéquations',
    description: 'Résolution d\'équations et d\'inéquations',
    classLevel: '2nde',
    category: 'algebra',
    difficulty: 'intermediate',
    estimatedTime: 65,
    prerequisites: [],
    color: '#ff6b6b',
    icon: 'x≤a',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 67
  },
  {
    id: '2nde-geometrie-plane-repere',
    title: 'Géométrie plane et repère',
    description: 'Géométrie analytique, vecteurs, coordonnées',
    classLevel: '2nde',
    category: 'geometry',
    difficulty: 'intermediate',
    estimatedTime: 65,
    prerequisites: [],
    color: '#ff6b6b',
    icon: '→',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 68
  },
  {
    id: '2nde-statistiques-probabilites',
    title: 'Statistiques et probabilités',
    description: 'Statistiques descriptives, probabilités de base',
    classLevel: '2nde',
    category: 'statistics',
    difficulty: 'intermediate',
    estimatedTime: 55,
    prerequisites: [],
    color: '#ff6b6b',
    icon: '📊',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 69
  },
  {
    id: '2nde-algorithmes-programmation',
    title: 'Algorithmes et programmation',
    description: 'Algorithmes, Python, structures de données',
    classLevel: '2nde',
    category: 'programming',
    difficulty: 'intermediate',
    estimatedTime: 50,
    prerequisites: [],
    color: '#ff6b6b',
    icon: '🐍',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 70
  },

  // 1ère - Lycée (chapitres existants restaurés)
  {
    id: 'equations-second-degre',
    title: 'Équations du second degré',
    description: 'Résolution d\'équations du second degré, discriminant, formes canonique et factorisée',
    classLevel: '1ere',
    category: 'algebra',
    difficulty: 'intermediate',
    estimatedTime: 120,
    prerequisites: [],
    color: '#8b5cf6',
    icon: '𝑥²',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 71
  },
  {
    id: 'nombres-derives',
    title: 'Nombres dérivés',
    description: 'Introduction au concept de dérivée, calcul du nombre dérivé en un point',
    classLevel: '1ere',
    category: 'analysis',
    difficulty: 'intermediate',
    estimatedTime: 90,
    prerequisites: [],
    color: '#06b6d4',
    icon: 'f\'',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 72
  },
  {
    id: 'fonctions-references-derivees',
    title: 'Fonctions de références et dérivées',
    description: 'Étude des fonctions de référence et calcul de leurs dérivées',
    classLevel: '1ere',
    category: 'analysis',
    difficulty: 'intermediate',
    estimatedTime: 100,
    prerequisites: [],
    color: '#06b6d4',
    icon: '∫',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 73
  },
  {
    id: 'fonctions-derivees',
    title: 'Fonctions dérivées',
    description: 'Calcul de dérivées, règles de dérivation, applications',
    classLevel: '1ere',
    category: 'analysis',
    difficulty: 'intermediate',
    estimatedTime: 110,
    prerequisites: [],
    color: '#06b6d4',
    icon: 'dy/dx',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 74
  },
  {
    id: 'exponentielle',
    title: 'Exponentielle',
    description: 'La fonction exponentielle, ses propriétés et applications',
    classLevel: '1ere',
    category: 'analysis',
    difficulty: 'advanced',
    estimatedTime: 95,
    prerequisites: [],
    color: '#06b6d4',
    icon: 'eˣ',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 75
  },
  {
    id: 'suites-arithmetiques-geometriques',
    title: 'Suites arithmétiques et géométriques et autres suites',
    description: 'Étude des suites arithmétiques, géométriques et autres types de suites',
    classLevel: '1ere',
    category: 'analysis',
    difficulty: 'intermediate',
    estimatedTime: 130,
    prerequisites: [],
    color: '#06b6d4',
    icon: 'uₙ',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 76
  },
  {
    id: 'generation-suite',
    title: 'Génération d\'une suite',
    description: 'Modes de génération des suites, formules de récurrence',
    classLevel: '1ere',
    category: 'analysis',
    difficulty: 'intermediate',
    estimatedTime: 85,
    prerequisites: [],
    color: '#06b6d4',
    icon: 'uₙ₊₁',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 77
  },
  {
    id: 'somme-termes-suite',
    title: 'Somme des termes d\'une suite',
    description: 'Calcul de sommes de termes de suites arithmétiques et géométriques',
    classLevel: '1ere',
    category: 'analysis',
    difficulty: 'intermediate',
    estimatedTime: 75,
    prerequisites: [],
    color: '#06b6d4',
    icon: 'Σ',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 78
  },
  {
    id: 'etude-suites',
    title: 'Étude de suites',
    description: 'Monotonie, convergence et limites de suites',
    classLevel: '1ere',
    category: 'analysis',
    difficulty: 'advanced',
    estimatedTime: 105,
    prerequisites: [],
    color: '#06b6d4',
    icon: 'lim',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 79
  },
  {
    id: 'trigonometrie',
    title: 'Trigonométrie',
    description: 'Cercle trigonométrique, fonctions sinus et cosinus, résolution d\'équations',
    classLevel: '1ere',
    category: 'geometry',
    difficulty: 'intermediate',
    estimatedTime: 115,
    prerequisites: [],
    color: '#10b981',
    icon: 'sin θ',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 80
  },
  {
    id: 'produit-scalaire',
    title: 'Produit scalaire',
    description: 'Définition et propriétés du produit scalaire, applications géométriques',
    classLevel: '1ere',
    category: 'geometry',
    difficulty: 'intermediate',
    estimatedTime: 120,
    prerequisites: [],
    color: '#10b981',
    icon: 'u⃗·v⃗',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 81
  },
  {
    id: 'equation-cartesienne',
    title: 'Équation cartésienne',
    description: 'Équations de droites et cercles dans le plan cartésien',
    classLevel: '1ere',
    category: 'geometry',
    difficulty: 'intermediate',
    estimatedTime: 90,
    prerequisites: [],
    color: '#10b981',
    icon: 'ax+by=c',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 82
  },
  {
    id: 'probabilites-conditionnelles',
    title: 'Probabilités conditionnelles',
    description: 'Probabilités conditionnelles, formule de Bayes, arbres de probabilité',
    classLevel: '1ere',
    category: 'probability',
    difficulty: 'intermediate',
    estimatedTime: 100,
    prerequisites: [],
    color: '#f59e0b',
    icon: 'P(A|B)',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 83
  },
  {
    id: 'probabilite-evenements-independants',
    title: 'Probabilité et événements indépendants',
    description: 'Événements indépendants, probabilités composées',
    classLevel: '1ere',
    category: 'probability',
    difficulty: 'intermediate',
    estimatedTime: 85,
    prerequisites: [],
    color: '#f59e0b',
    icon: 'P(A∩B)',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 84
  },
  {
    id: 'probabilite-variables-aleatoires',
    title: 'Probabilité et variables aléatoires',
    description: 'Variables aléatoires discrètes, espérance, variance',
    classLevel: '1ere',
    category: 'probability',
    difficulty: 'advanced',
    estimatedTime: 110,
    prerequisites: [],
    color: '#f59e0b',
    icon: 'E(X)',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 85
  },

  // Terminale - Lycée
  {
    id: 'terminale-limites-continuite',
    title: 'Limites et continuité',
    description: 'Limites de fonctions, continuité, théorèmes',
    classLevel: 'terminale',
    category: 'analysis',
    difficulty: 'advanced',
    estimatedTime: 90,
    prerequisites: [],
    color: '#45b7d1',
    icon: 'lim',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 86
  },
  {
    id: 'terminale-derivation-avance',
    title: 'Dérivation avancée',
    description: 'Dérivation, primitives, théorèmes fondamentaux',
    classLevel: 'terminale',
    category: 'analysis',
    difficulty: 'advanced',
    estimatedTime: 85,
    prerequisites: [],
    color: '#45b7d1',
    icon: '∫',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 87
  },
  {
    id: 'terminale-logarithme',
    title: 'Fonction logarithme',
    description: 'Fonction logarithme népérien, propriétés',
    classLevel: 'terminale',
    category: 'analysis',
    difficulty: 'advanced',
    estimatedTime: 75,
    prerequisites: [],
    color: '#45b7d1',
    icon: 'ln',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 88
  },
  {
    id: 'terminale-geometrie-vectorielle',
    title: 'Géométrie vectorielle',
    description: 'Vecteurs dans l\'espace, équations de plans',
    classLevel: 'terminale',
    category: 'geometry',
    difficulty: 'advanced',
    estimatedTime: 70,
    prerequisites: [],
    color: '#45b7d1',
    icon: '⃗v',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 89
  },
  {
    id: 'terminale-lois-probabilites',
    title: 'Lois de probabilités',
    description: 'Lois discrètes, continues, théorème central limite',
    classLevel: 'terminale',
    category: 'statistics',
    difficulty: 'advanced',
    estimatedTime: 80,
    prerequisites: [],
    color: '#45b7d1',
    icon: 'X~N(μ,σ²)',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 90
  },
  {
    id: 'terminale-algorithmes-complexes',
    title: 'Algorithmes complexes',
    description: 'Algorithmes avancés, complexité, applications',
    classLevel: 'terminale',
    category: 'programming',
    difficulty: 'advanced',
    estimatedTime: 65,
    prerequisites: [],
    color: '#45b7d1',
    icon: '🖥️',
    lessons: [],
    exercises: [],
    isLocked: false,
    order: 91
  }
];

export const getChaptersByClass = (classLevel: ClassLevel) => {
  return chaptersData
    .filter(chapter => 
      chapter.classLevel === classLevel && !hiddenChapters.includes(chapter.id)
    )
    .sort((a, b) => a.order - b.order);
};

export const getChaptersByCategory = (category: string) => {
  return chaptersData.filter(chapter => chapter.category === category);
};

export const getChaptersByClassAndCategory = (classLevel: ClassLevel, category: string) => {
  return chaptersData.filter(chapter => 
    chapter.classLevel === classLevel && 
    chapter.category === category &&
    !hiddenChapters.includes(chapter.id)
  );
};

export const getChapterById = (id: string) => {
  return chaptersData.find(chapter => chapter.id === id);
};

export const getAvailableClassLevels = (): ClassLevel[] => {
  const levels = Array.from(new Set(chaptersData.map(chapter => chapter.classLevel)));
  return levels as ClassLevel[];
};

export const getChaptersGroupedByClass = () => {
  const grouped: { [key in ClassLevel]?: Chapter[] } = {};
  
  chaptersData.forEach(chapter => {
    // Exclure les chapitres cachés de l'affichage
    if (hiddenChapters.includes(chapter.id)) {
      return;
    }
    
    if (!grouped[chapter.classLevel]) {
      grouped[chapter.classLevel] = [];
    }
    grouped[chapter.classLevel]!.push(chapter);
  });
  
  return grouped;
};

export const getSubChapters = (parentChapterId: string) => {
  return chaptersData.filter(chapter => chapter.parentChapter === parentChapterId);
}; 